# Generated by Django 4.2.4 on 2023-08-22 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='survey',
            unique_together={('name', 'creator')},
        ),
    ]
